In [1]:
import pandas as pd

In [6]:
df = pd.read_excel("mst.xlsx")

In [7]:
df

,"Sri Aurobindo Institute of Technology, Indore",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Department of Computer Science & Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MST- I Mark Sheet (May-June 2026) Section-CS-4A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S. No.,Enrollment no.,Student Name,BT-401(M-III),CS-402(ADA),CS-403(SE),CS-404(COA),CS-405(OS),NaN,Note:,NaN
3,1,0873CS231003,ADESH SINGH,1,ABS,0,0,0,NaN,Mark Absent,ABS
4,2,0873CS231022,Avinash Verma,12,0,19,6,8,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
57,55,0873CS241058,GAYATRI BASORE,ABS,ABS,ABS,ABS,ABS,NaN,NaN,NaN
58,56,0873CS241059,GIRIRAJ SOLANKI,1,1,0,0,3,NaN,NaN,NaN
59,57,0873CS241060,GOURAV VERMA(BA),ABS,ABS,ABS,ABS,ABS,NaN,NaN,NaN
60,58,0873CS241061,GOURAV YADAV,11,0,5,0,8,NaN,NaN,NaN
61,59,0873CS241062,GOVIND,0,0,4,0,1,NaN,NaN,NaN

In [11]:
df = df.dropna(columns=[[unnamed:8,un])

SyntaxError: invalid syntax (2486699960.py, line 1)

In [9]:
df

Empty DataFrame
Columns: [Sri Aurobindo Institute of Technology, Indore, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10]
Index: []